// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website.Common;

#nullable disable

namespace Website.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240329020617_Dynamic")]
    partial class Dynamic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("ImageStreamPost", b =>
                {
                    b.Property<Guid>("AttachedImagesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StreamsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AttachedImagesId", "StreamsId");

                    b.HasIndex("StreamsId");

                    b.ToTable("ImageStreamPost");
                });

            modelBuilder.Entity("Website.Models.Database.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Website.Models.Database.ShortLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShortLinks");
                });

            modelBuilder.Entity("Website.Models.Database.ShortLinkHit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLinkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShortLinkId");

                    b.ToTable("ShortLinkHits");
                });

            modelBuilder.Entity("Website.Models.Database.StreamPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Posted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("ImageStreamPost", b =>
                {
                    b.HasOne("Website.Models.Database.Image", null)
                        .WithMany()
                        .HasForeignKey("AttachedImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Website.Models.Database.StreamPost", null)
                        .WithMany()
                        .HasForeignKey("StreamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Website.Models.Database.ShortLinkHit", b =>
                {
                    b.HasOne("Website.Models.Database.ShortLink", "ShortLink")
                        .WithMany("Hits")
                        .HasForeignKey("ShortLinkId");

                    b.Navigation("ShortLink");
                });

            modelBuilder.Entity("Website.Models.Database.ShortLink", b =>
                {
                    b.Navigation("Hits");
                });
#pragma warning restore 612, 618
        }
    }
}
