# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        # Login to the NESO registry
        - name: Docker Login
          uses: docker/login-action@v1.12.0
          with:
            registry: https://registry.dominicmaas.co.nz
            username: ${{ secrets.NESO_USERNAME }}
            password: ${{ secrets.NESO_PASSWORD }}

        - name: 'Setup Docker BuildX'
          uses: docker/setup-buildx-action@v1

        - name: 'Build and Push Image'
          uses: docker/build-push-action@v2
          with:
            context: src/Website/
            push: true
            tags: registry.dominicmaas.co.nz/personal-website:latest
