# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build web/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/personal-website:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/personal-website:latest

        #- name: 'Deploy to Azure Container Instances'
        #  uses: 'azure/aci-deploy@v1'
        #  with:
        #    resource-group: ${{ secrets.RESOURCE_GROUP }}
        #    dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        #    image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/personal-website:latest
        #    registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #    registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #    registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #    name: personal-website
        #    location: 'west us'