# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Login to container registry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: 'Setup Docker BuildX'
          uses: docker/setup-buildx-action@v1

        - name: 'Build and Push Image'
          uses: docker/build-push-action@v2
          with:
            context: web/
            push: true
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/personal-website:latest
            secrets: |
              AzureKeyVault__ClientId=${{ secrets.AZKV_CLIENT_ID }}
              AzureKeyVault__ClientSecret=${{ secrets.AZKV_CLIENT_SECRET }}